#! /bin/sh
g=/proj/simetaw/gdb; 
b=$g/etosimetaw; 
for y in `seq $1 $2`; do 
    echo -n "$y "
#    for m in 11 ; do
    for m in 01 02 03 04 05 06 07 08 09 10 11 12; do
	echo -n "$m "
      for d in `echo $b/$y/$y-${m}-??`; do 
	  day=`basename $d`; 
	  if (g.mapset mapset=$day location=$y gisdbase=$b 2>/dev/null >/dev/null); then 
#	      g.remove PCP,ETh,ETo,RD 2>/dev/null >/dev/null;
#	      rm -f ${b}/${y}/${day}/etc/TnTxPCPEToRF.csv;
	      make-eto TnTxPCPEToRF.csv
	  fi; 
      done;
      if (g.mapset mapset=${y}-${m} location=$y 2>/dev/null > /dev/null); then
	  make-eto TnTxPCPNRF.csv
      fi;
    done
    echo '';
done